#!/usr/bin/env perl
#       project-starter
#       =  Copyright 2011 Xiong Changnian <xiong@cpan.org>   =
#       = Free Software = Artistic License 2.0 = NO WARRANTY =

use 5.014002;
use strict;
use warnings;

use lib qw| lib util/lib |;              # development only

use Project::Starter;

exit Project::Starter::main(@ARGV);

__END__
